# Generated by Django 5.1.6 on 2025-03-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iostreakApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Subject',
            field=models.CharField(max_length=50),
        ),
    ]
