# Generated by Django 5.1.6 on 2025-03-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iostreakApi', '0002_alter_contactus_email_alter_contactus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Subject',
            field=models.CharField(max_length=100),
        ),
    ]
